package javaException;

public class ExceptionQ1 {

	public static void main (String args[]) {
	    
	      int num1 = 30, num2 = 0;
	      int result = 0;
	      try {
	         result = num1/num2;
	         System.out.println(" Result is" +result);
	         
	        
	      
	      } catch (ArithmeticException e) {
	         System.out.println ("Can't be divided by Zero"+e);
	      }
	   }
	
	
}
